[package]
name = "redos"
version = "0.1.0"
authors = ["jiang <392711804@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.11"
volatile = "0.4.2"
lazy_static = {version = "1.4.0", features = ["spin_no_std"]}
spin = "0.7.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# See https://github.com/rust-osdev/bootimage
[package.metadata.bootimage]

build-command = ["xbuild"]
