[package]
name = "redos"
version = "0.1.0"
authors = ["jiang <392711804@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_arch = "x86_64")'.dependencies]
bootloader = "0.9.11"

[target.'cfg(target_arch = "riscv64")'.dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# See https://github.com/rust-osdev/bootimage
[package.metadata.bootimage]
test-timeout = 300          # (in seconds)
build-command = ["xbuild"]
